# Generated by Django 5.2.10 on 2026-02-01 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_form_success_link_form_success_link_label_and_more'),
        ('quizzes', '0004_quiz_instructions'),
        ('recruitment', '0001_initial'),
        ('users', '0013_alter_memberprofile_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentdrive',
            name='assessment_instructions',
            field=models.TextField(blank=True, help_text='Instructions for the file upload assessment'),
        ),
        migrations.AddField(
            model_name='recruitmentdrive',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_drives', to='core.form'),
        ),
        migrations.AddField(
            model_name='recruitmentdrive',
            name='primary_field',
            field=models.CharField(blank=True, help_text='Field label in form to use as UID (e.g. Email / Roll Number)', max_length=200),
        ),
        migrations.AddField(
            model_name='recruitmentdrive',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_drives', to='quizzes.quiz'),
        ),
        migrations.CreateModel(
            name='RecruitmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='recruitment/assignments/')),
                ('external_link', models.URLField(blank=True, help_text='Link to external assignment doc/folder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='recruitment.recruitmentdrive')),
                ('sig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_assignments', to='users.sig')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('candidate_name', models.CharField(blank=True, max_length=255)),
                ('assessment_file', models.FileField(blank=True, null=True, upload_to='recruitment/assessments/')),
                ('solution_link', models.URLField(blank=True, help_text='Link to hosted solution (Drive/GitHub)')),
                ('assessment_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('interview_time', models.DateTimeField(blank=True, null=True)),
                ('oa_score', models.FloatField(blank=True, null=True)),
                ('assessment_score', models.FloatField(blank=True, null=True)),
                ('interview_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('OA_PENDING', 'OA Pending'), ('OA_COMPLETED', 'OA Completed'), ('ASSESSMENT_PENDING', 'Assessment Pending'), ('ASSESSMENT_COMPLETED', 'Assessment Completed'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.recruitmentdrive')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('drive', 'identifier')},
            },
        ),
    ]
