# Generated by Django 5.2.10 on 2026-01-23 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_projects', models.BooleanField(default=False)),
                ('can_manage_events', models.BooleanField(default=False)),
                ('can_manage_team', models.BooleanField(default=False)),
                ('can_manage_gallery', models.BooleanField(default=False)),
                ('can_manage_announcements', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('description', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.role'),
        ),
    ]
