# Generated by Django 5.2.10 on 2026-01-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_memberprofile_user_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='sig',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='year_of_joining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='team_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='year',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
