# Generated by Django 5.2.10 on 2026-01-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_memberprofile_department_memberprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'ordering': ['order', 'full_name']},
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
