# Generated by Django 5.2.10 on 2026-01-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_memberprofile_options_memberprofile_is_alumni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('url', 'URL Link'), ('number', 'Number'), ('date', 'Date'), ('textarea', 'Long Text')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='sig',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
