# Generated by Django 5.2.10 on 2026-01-23 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profilefielddefinition_sig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rank', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.AddField(
            model_name='profilefielddefinition',
            name='limit_to_sig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='users.sig'),
        ),
    ]
